# Generated by Django 5.1.3 on 2024-11-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='created',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='linenos',
        ),
    ]
